#!/bin/bash
set -euxo pipefail; IFS=$'\n\t'

sudo -v

# Wait Nomad
until nomad acl policy list > /dev/null; do
  sleep 1; done;

NOMAD_ACL_BOOTSTRAP="$(nomad acl bootstrap)"

NOMAD_ACCESSOR_ID="$(echo "$NOMAD_ACL_BOOTSTRAP" | grep 'Accessor ID' | rev | cut -d' ' -f1 | rev)"
NOMAD_TOKEN="$(echo "$NOMAD_ACL_BOOTSTRAP" | grep 'Secret ID' | rev | cut -d' ' -f1 | rev)"

# Write NOMAD_TOKEN as a local file
echo "NOMAD_TOKEN=$NOMAD_TOKEN" >> "/etc/environment"
