name: Lint

on: [push, pull_request]

jobs:
  tf-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: terraform -chdir=terraform fmt -check -diff -recursive

  hcl-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'

      - name: Install hclfmt
        run: go get -u 'github.com/hashicorp/hcl/v2/cmd/hclfmt'

      - name: Run hclfmt
        run: |
          for f in **/*.{nomad,hcl}; do
            hclfmt \
              -check \
              -require-no-change \
              -w \
              "$f"
          done

  # This name is used by status check requirement
  before-cd-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Nomad
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y nomad
          echo "nomad_version: $(nomad -v)"

      - name: Validate job files
        run: |
          for job in jobs/*.nomad; do
            nomad job validate "$job";
          done

      - name: Start a Nomad Agent
        run: sudo nomad agent -dev -config nomad/development.hcl &

      - name: Wait for initializing...
        timeout-minutes: 5
        run: |
          until nomad node status > /dev/null; do
            sleep 1; done;

      - name: Run a Nomad job
        run: |
          nomad job run jobs/development/mysql.nomad
          nomad job run jobs/development/memcached.nomad
          nomad job run jobs/development/fastcgi.nomad
          nomad job run jobs/development/http.nomad
          nomad job run jobs/development/parsoid.nomad
          nomad job run jobs/development/restbase.nomad
          nomad job run jobs/development/mathoid.nomad

      - name: Access MediaWiki until success
        timeout-minutes: 5
        run: |
          echo 'Waiting for http...'
          until curl -sLfo /dev/null localhost; do
            sleep 1; done

          echo 'Waiting for parsoid...'
          until [ -n "$(docker ps -qf 'name=^parsoid')" ]; do
            sleep 1; done
          ID="$(docker ps -qf 'name=^parsoid')"
          until [ "$(docker inspect "$ID" --format='{{json .State.Health.Status}}')" = \"healthy\" ]; do
            sleep 1; done

      - name: Test VisualEditor API
        run: |
          curl -sSLvo /dev/null "http://localhost/api.php?action=visualeditor&page=arbitrary_page&paction=parse&wikitext=arbitrary"
          curl -sSLvo /dev/null "http://localhost/localhost/v1/"

      - name: backup of accessing
        if: ${{ failure() }}
        run: |
          echo 'Failed to connect to localhost';
          function header {
            line="--------------------------------------------------------"
            echo -e "$line\n$1\n$line"
          }
          header "journalctl"
          journalctl -u nomad
          header "docker images"
          docker image ls --no-trunc
          header "nomad status"
          nomad status
          for JOB in mysql memcached fastcgi http parsoid restbase mathoid; do
            header "nomad job '$JOB' status"
            nomad job status "$JOB"
            allocs=$(nomad job status "$JOB" | awk '/Allocations/,0' | tail -n +3 | awk '{if($6=="failed")print $1}')
            for ALLOC in $allocs; do
              header "[$JOB] Allocation '$ALLOC' status"
              nomad alloc status "$ALLOC";
              task=$(nomad alloc status -short "$ALLOC" | tail -n1 | awk '{print $1}')
              header "[$JOB] Allocation '$ALLOC' stdout logs "
              nomad alloc logs "$ALLOC" $task;
              header "[$JOB] Allocation '$ALLOC' stderr logs "
              nomad alloc logs -stderr "$ALLOC" $task;
            done
          done
          curl -sSLv localhost || true
