name: Lint

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: terraform -chdir=terraform fmt -check -diff -recursive
