name: Lint, test and publish

on: [push, pull_request]

jobs:
  lint:
    name: PHP lint
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP Action
      uses: shivammathur/setup-php@1.7.2
      with:
        php-version: '7.3'
    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - run: |
        composer install --prefer-source --quiet --no-interaction
        composer test

  docker_image:
    name: Docker image test and publishing
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Edit configuration
      run: |
        mv configs/secret.php.example configs/secret.php;
        sed -i -r 's/localhost/127.0.0.1/' configs/secret.php

    # TODO port to Nomad
    # - name: Initialize docker swarm and start services
    #   run: |
    #     docker swarm init
    #     docker stack deploy -c development.yml mediawiki

    - name: Access 127.0.0.1 until success
      timeout-minutes: 3
      run: |
        printf 'Waiting for http...'
        until curl -sLfo /dev/null 127.0.0.1; do
          sleep 1;
          printf '.';
        done; printf '\n'
    # TODO port to Nomad
    # - name: backup of accessing
    #   if: ${{ failure() }}
    #   run: |
    #     echo 'Failed to connect to 127.0.0.1';
    #     docker ps;
    #     for s in $(docker service ls -q ); do docker service ps "$s"; done
    #     docker container ps;
    #     for s in $(docker service ls -q ); do docker service logs "$s"; done
    # - name: Try to access the mediawiki
    #   run: curl -sSLvo /dev/null 127.0.0.1 || docker service logs mediawiki_fastcgi
