name: Test

on: [push, pull_request]

jobs:
  docker_image:
    name: Test Nomad job specification
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Nomad
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y nomad
          echo "::set-output name=nomad_version::$(nomad -v)"

      - name: Validate job files
        run: |
          for job in jobs/*.nomad; do
            nomad job validate "$job";
          done

      - name: Start a Nomad Agent
        run: |
          mv nomad/development.example.hcl nomad/development.hcl
          sed -i -r "s#/path/to/configs#${PWD}/configs#" nomad/development.hcl
          sudo nomad agent -dev -config nomad/development.hcl &

      - name: Wait for initializing...
        run: |
          until nomad node status > /dev/null; do
            sleep 1; done;

      - name: Prepare configuration
        run: |
          curl -L https://raw.githubusercontent.com/femiwiki/docker-mediawiki/main/configs/secret.php.example -o configs/secret.php

      - name: Run a Nomad job
        run: |
          nomad job run jobs/development/mysql.nomad
          nomad job run jobs/development/memcached.nomad
          nomad job run jobs/development/fastcgi.nomad
          nomad job run jobs/development/http.nomad
          nomad job run jobs/development/parsoid.nomad
          nomad job run jobs/development/restbase.nomad
          nomad job run jobs/development/mathoid.nomad

      - name: Access localhost until success
        timeout-minutes: 5
        run: |
          until curl -sLfo /dev/null localhost; do
            sleep 1;
          done;
      - name: backup of accessing
        if: ${{ failure() }}
        run: |
          echo 'Failed to connect to localhost';
          function header {
            line="--------------------------------------------------------"
            echo -e "$line\n$1\n$line"
          }
          header "docker images"
          docker image ls --no-trunc
          header "nomad status"
          nomad status
          for JOB in mysql memcached fastcgi http parsoid restbase mathoid; do
            header "nomad job '$JOB' status"
            nomad job status "$JOB"
            allocs=$(nomad job status "$JOB" | awk '/Allocations/,0' | tail -n +3 | awk '{if($6=="failed")print $1}')
            for ALLOC in $allocs; do
              header "Allocation '$ALLOC' status"
              nomad alloc status "$ALLOC";
              task=$(nomad alloc status -short "$ALLOC" | tail -n1 | awk '{print $1}')
              header "Allocation '$ALLOC' stdout logs "
              nomad alloc logs "$ALLOC" $task;
              header "Allocation '$ALLOC' stderr logs "
              nomad alloc logs -stderr "$ALLOC" $task;
            done
          done
          curl -sSLv localhost || true
      - name: Try to access the mediawiki
        run: curl -sSLvo /dev/null localhost
      - name: Test VisualEditor API
        run: curl -sSLvo /dev/null "http://localhost/api.php?action=visualeditor&format=json&page=main_page&paction=parse&wikitext='''foo'''"
