name: Test

on: [push, pull_request]

jobs:
  docker_image:
    name: Test Nomad job specification
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Nomad and Consul
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y nomad consul
          echo "::set-output name=consul_version::$(consul -v)"
          echo "::set-output name=nomad_version::$(nomad -v)"

      - name: Validate job files
        run: |
          for job in jobs/*.nomad; do
            nomad job validate "$job";
          done

      - name: Start a Nomad Agent and a Consul agent
        run: |
          mv nomad/development.example.hcl nomad/development.hcl
          sed -i -r "s#/path/to/configs#${PWD}/configs#" nomad/development.hcl
          sudo nomad agent -dev-connect -config nomad/development.hcl &
          consul agent -dev -bootstrap &

      - name: Wait for initializing...
        run: |
          NODE_ID="$(nomad node status -self | head -1 | awk '{print $3}')"
          until [[ $(curl -s "http://127.0.0.1:4646/v1/node/$NODE_ID") = *"consul.version"* ]]; do
            sleep 1; done;

      - name: Prepare configuration
        run: |
          curl -L https://raw.githubusercontent.com/femiwiki/docker-mediawiki/main/configs/secret.php.example -o configs/secret.php

      - name: Run a Nomad job
        run: |
          nomad job run jobs/development/mysql.nomad
          nomad job run jobs/development/memcached.nomad
          nomad job run jobs/development/fastcgi.nomad
          nomad job run jobs/development/http.nomad
          nomad job run jobs/development/parsoid.nomad
          nomad job run jobs/development/restbase.nomad
          nomad job run jobs/development/mathoid.nomad

      - name: Access localhost until success
        timeout-minutes: 10
        run: |
          until curl -sLfo /dev/null localhost; do
            sleep 1;
          done;
      - name: backup of accessing
        if: ${{ failure() }}
        run: |
          echo 'Failed to connect to localhost';
          line='--------------------------------------------------------'
          nomad status
          for job in mysql memcached fastcgi http parsoid restbase mathoid; do
            nomad job status "$job"
            allocs=$(nomad job status "$job" | awk '/Allocations/,0' | tail -n +3 | awk '{if($6=="failed")print $1}')
            for s in $allocs; do
              echo "Allocation $s status $line";
              nomad alloc status "$s";
              task=$(nomad alloc status -short "$s" | tail -n1 | awk '{print $1}')
              echo "Allocation $s stdout logs $line";
              nomad alloc logs "$s" $task;
              echo "Allocation $s stderr logs $line";
              nomad alloc logs -stderr "$s" $task;
            done
            echo "curl $line";
          done
          curl -sSLv localhost || true
      - name: Try to access the mediawiki
        run: curl -sSLvo /dev/null localhost
      - name: Test VisualEditor API
        run: curl -sSLvo /dev/null "http://localhost/api.php?action=visualeditor&format=json&page=main_page&paction=parse&wikitext='''foo'''"
